# Docker Hub + HuggingFace Integration Configuration - Development
version: '3.8'

services:
  # Main GAN-HTR training service for development
  gan-htr:
    build:
      context: ./docRestoration
      dockerfile: Dockerfile
    image: jatnikonm/gan-htr:local
    container_name: gan-htr-local
    restart: unless-stopped
    volumes:
      # Local source code mounting
      - ./docRestoration:/workspace
      - ./network:/workspace/network
      # Training outputs
      - ./outputs:/workspace/outputs
      - ./logbook:/workspace/logbook
      # MLflow runs
      - ./mlruns:/workspace/mlruns
    environment:
      - CUDA_VISIBLE_DEVICES=0
      - TF_FORCE_GPU_ALLOW_GROWTH=true
      - PYTHONUNBUFFERED=1
      - HF_HUB_ENABLE_HF_TRANSFER=1
      - MODE=development
    ports:
      - "5000:5000/tcp"
      - "6006:6006/tcp"
      - "8888:8888/tcp"
    tty: true
    stdin_open: true
    # Entrypoint handles auto-download or development mode
    entrypoint: ["/docRestoration/entrypoint.sh"]
    command: ["python3", "/workspace/dual_modal_gan/scripts/train.py"]
    networks:
      - default

  # Development workspace (for local development)
  dev:
    image: python:3.10
    build:
      context: ./docRestoration
      dockerfile: Dockerfile.dev
      args:
        - PYTHONPATH=/usr/local/bin/python
    working_dir: /workspace/docRestoration
    volumes:
      - ./docRestoration:/workspace/docRestoration
      - ./outputs:/workspace/outputs
      - ./mlruns:/workspace/mlruns
    environment:
      - DEVELOPMENT_MODE=true
      - DEBUG=true
      - MODE=development
    command: bash
    depends_on:
      - dev-setup
    networks:
      - default

  # Setup service for development dependencies
  dev-setup:
    image: python:3.10
    command: >
      bash -c "
      echo '🔧 Setting up development environment...'
      python3 -m pip install --upgrade pip
      python3 -m pip install huggingface_hub datasets
      python3 -m pip install poetry
      poetry --version
      poetry self update
      poetry install
      "
    volumes:
      - ./docRestoration:/workspace/docRestoration
    environment:
      - DEV_SETUP=true
    networks:
      - default

  # MLflow experiment tracking
  mlflow:
    image: python:3.10
    ports:
      - "5000:5000/tcp"
    volumes:
      - ./mlruns:/mlflow/mlruns
      - ./outputs:/workspace/outputs
    command: >
      bash -c "
      poetry run python3 scripts/download_data.sh
      poetry run python3 scripts/evaluate_cer_wer.py
      "
    depends_on:
      - dev-setup
    networks:
      - default

# Volume definitions
volumes:
  mlruns:
    driver: local
  docrestoration-data:
    driver: local

# Network configuration
networks:
  default:
    driver: bridge