#!/bin/bash
# Quick Reference: Fine-tuning Commands

echo "╔════════════════════════════════════════════════════════════════╗"
echo "║          FINE-TUNING QUICK REFERENCE                           ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""

echo "📋 STEP 1: Create Dataset (Manual - Optional)"
echo "   poetry run python scripts/create_finetuning_strips.py \\"
echo "       --gt_dir DokumenRusak/manual_restoration/gt \\"
echo "       --deg_dir DokumenRusak/manual_restoration/deg \\"
echo "       --output_dir dual_modal_gan/data/finetuning \\"
echo "       --augment"
echo ""

echo "📋 STEP 2: Launch Fine-tuning (Recommended - All-in-one)"
echo "   ./scripts/launch_finetuning.sh"
echo ""

echo "📋 STEP 3: Monitor Training"
echo "   tail -f logs/finetuning/finetuning_*.log"
echo ""

echo "📋 Alternative: Manual Training Launch"
echo "   nohup ./scripts/universal_train_from_json.sh \\"
echo "       configs/thin_stroke_preservation_v1_finetuning.json \\"
echo "       > logs/finetuning/manual_$(date +%Y%m%d_%H%M%S).log 2>&1 &"
echo ""

echo "═══════════════════════════════════════════════════════════════"
echo "📊 EXPECTED DATASET SIZE"
echo "═══════════════════════════════════════════════════════════════"
echo "   Source:  1 full-page image (4013 x 2735 px)"
echo "   Strips:  31 horizontal strips @ 128px height"
echo "   Augment: 5x (flip + brightness + contrast)"
echo "   Total:   155 samples (31 × 5)"
echo ""
echo "   Split Strategy: Sequential (NO data leakage)"
echo "   ├─ Train (70%):  108 samples (top strips)"
echo "   ├─ Val (15%):     23 samples (middle strips)"  
echo "   └─ Test (15%):    24 samples (bottom strips)"
echo ""

echo "═══════════════════════════════════════════════════════════════"
echo "🎯 KEY CONFIGURATION"
echo "═══════════════════════════════════════════════════════════════"
echo "   Base Model:  thin_stroke_preservation_v1_academic (ckpt-99)"
echo "   LR:          1e-5 (10x reduction from base 2e-4)"
echo "   Epochs:      15 (minimal to prevent catastrophic forgetting)"
echo "   Patience:    8 (early stopping)"
echo "   Metric:      PSNR only (visual quality focus)"
echo ""

echo "═══════════════════════════════════════════════════════════════"
echo "⚠️  IMPORTANT NOTES"
echo "═══════════════════════════════════════════════════════════════"
echo "   ✓ Sequential split prevents data leakage"
echo "   ✓ Low LR prevents catastrophic forgetting"
echo "   ✓ Early stopping prevents overfitting"
echo "   ✗ Only 1 document - domain-specific adaptation"
echo "   ✗ Do NOT claim generalization in papers"
echo ""

echo "═══════════════════════════════════════════════════════════════"
echo "📁 OUTPUT LOCATIONS"
echo "═══════════════════════════════════════════════════════════════"
echo "   Dataset:      dual_modal_gan/data/finetuning/"
echo "   Checkpoints:  dual_modal_gan/checkpoints/thin_stroke_preservation_v1_finetuning/"
echo "   Best Model:   dual_modal_gan/checkpoints/thin_stroke_preservation_v1_finetuning/best_model/"
echo "   Samples:      dual_modal_gan/outputs/samples_thin_stroke_preservation_v1_finetuning/"
echo "   Logs:         logs/finetuning/"
echo ""

echo "═══════════════════════════════════════════════════════════════"
echo "🔧 TROUBLESHOOTING"
echo "═══════════════════════════════════════════════════════════════"
echo "   Checkpoint not found:"
echo "     → ls dual_modal_gan/checkpoints/thin_stroke_preservation_v1_academic/best_model/"
echo ""
echo "   No image pairs:"
echo "     → ls DokumenRusak/manual_restoration/gt/"
echo "     → ls DokumenRusak/manual_restoration/deg/"
echo ""
echo "   OOM error:"
echo "     → Edit config: \"batch_size\": 1"
echo ""

echo "╔════════════════════════════════════════════════════════════════╗"
echo "║  Full guide: catatan/FINETUNING_GUIDE.md                       ║"
echo "╚════════════════════════════════════════════════════════════════╝"
