artifact_uri: file:///workspace/docRestoration/mlruns/128048753604076526/be504d90af1e479aaff9ebcd9080a4e7/artifacts
end_time: null
entry_point_name: ''
experiment_id: '128048753604076526'
lifecycle_stage: active
run_id: be504d90af1e479aaff9ebcd9080a4e7
run_name: whimsical-koi-632
run_uuid: be504d90af1e479aaff9ebcd9080a4e7
source_name: ''
source_type: 4
source_version: ''
start_time: 1760150216133
status: 1
tags: []
user_id: root
