artifact_uri: file:///workspace/docRestoration/mlruns/498988807487920372/7d9b2ad7066244c1ab7dbb08da366fcc/artifacts
end_time: null
entry_point_name: ''
experiment_id: '498988807487920372'
lifecycle_stage: active
run_id: 7d9b2ad7066244c1ab7dbb08da366fcc
run_name: secretive-hound-918
run_uuid: 7d9b2ad7066244c1ab7dbb08da366fcc
source_name: ''
source_type: 4
source_version: ''
start_time: 1760137717805
status: 1
tags: []
user_id: root
